In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Customer_Details.csv to Customer_Details.csv
Saving Delivery_Partner_Data.csv to Delivery_Partner_Data.csv
Saving Product_Details.csv to Product_Details.csv
Saving Sales_Channel.csv to Sales_Channel.csv
Saving Sales_Data.csv to Sales_Data.csv

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Delivery_Partner_Data.csv to Delivery_Partner_Data.csv

In [4]:
from google.colab import files

uploaded = files.upload()

Saving Product_Details.csv to Product_Details.csv
Saving Sales_Data.csv to Sales_Data.csv

In [5]:
from google.colab import files

uploaded = files.upload()

Saving Sales_Channel.csv to Sales_Channel.csv

In [4]:
customers = pd.read_csv("Customer_Details.csv")

In [5]:
customers.head()

,CustomerID,SignupDate,Gender,AgeBand,Segment,Tier,City,State,Region,PreferredChannel,ActivityWeight
0,500001,2022-03-20,Male,35-44,Young Professional,Tier-1,Hyderabad,Telangana,South,Flipkart,8.3345
1,500002,2021-10-19,Male,18-24,Student,Tier-1,Pune,Maharashtra,West,Flipkart,0.6440
2,500003,2023-10-10,Female,45+,Family Buyer,Tier-3,Raipur,Chhattisgarh,Central,Amazon India,0.3899
3,500004,2021-05-24,Female,18-24,Gamer,Tier-2,Nagpur,Maharashtra,West,Amazon India,0.4533
4,500005,2020-06-01,Female,25-34,Working Professional,Tier-3,Varanasi,Uttar Pradesh,North,Local Multi-brand Retail,0.8344

In [6]:
customers.shape

(150000, 11)

In [7]:
customers.isnull().sum()

CustomerID          0
SignupDate          0
Gender              0
AgeBand             0
Segment             0
Tier                0
City                0
State               0
Region              0
PreferredChannel    0
ActivityWeight      0
dtype: int64

In [10]:
(customers.isnull().sum() / len(customers)) * 100

CustomerID          0.0
SignupDate          0.0
Gender              0.0
AgeBand             0.0
Segment             0.0
Tier                0.0
City                0.0
State               0.0
Region              0.0
PreferredChannel    0.0
ActivityWeight      0.0
dtype: float64

In [8]:
customers.apply(lambda x: x.astype(str).str.strip().eq("").sum())

CustomerID          0
SignupDate          0
Gender              0
AgeBand             0
Segment             0
Tier                0
City                0
State               0
Region              0
PreferredChannel    0
ActivityWeight      0
dtype: int64

In [9]:
customers.duplicated().sum()

np.int64(0)

In [10]:
customers["CustomerID"].nunique()

150000

In [11]:
len(customers)

150000

In [12]:
customers.dtypes

CustomerID            int64
SignupDate           object
Gender               object
AgeBand              object
Segment              object
Tier                 object
City                 object
State                object
Region               object
PreferredChannel     object
ActivityWeight      float64
dtype: object

In [13]:
customers["SignupDate"] = pd.to_datetime(customers["SignupDate"])

In [14]:
customers.dtypes

CustomerID                   int64
SignupDate          datetime64[ns]
Gender                      object
AgeBand                     object
Segment                     object
Tier                        object
City                        object
State                       object
Region                      object
PreferredChannel            object
ActivityWeight             float64
dtype: object

In [15]:
text_columns = customers.select_dtypes(include="object").columns

customers[text_columns] = customers[text_columns].apply(
    lambda x: x.str.strip()
)

In [16]:
customers[text_columns] = customers[text_columns].apply(
    lambda x: x.str.replace(r"\s+", " ", regex=True)
)

In [17]:
customers["AgeBand"].describe()

count     150000
unique         4
top        25-34
freq       52708
Name: AgeBand, dtype: object

In [18]:
customers["SignupDate"].min(), customers["SignupDate"].max()

(Timestamp('2019-01-01 00:00:00'), Timestamp('2024-12-31 00:00:00'))

In [19]:
customers[customers["SignupDate"] > pd.Timestamp.today()]

Empty DataFrame
Columns: [CustomerID, SignupDate, Gender, AgeBand, Segment, Tier, City, State, Region, PreferredChannel, ActivityWeight]
Index: []

In [20]:
customers["Gender"].value_counts(dropna=False)

Gender
Male      93179
Female    56821
Name: count, dtype: int64

In [21]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   CustomerID        150000 non-null  int64
 1   SignupDate        150000 non-null  datetime64[ns]
 2   Gender            150000 non-null  object
 3   AgeBand           150000 non-null  object
 4   Segment           150000 non-null  object
 5   Tier              150000 non-null  object
 6   City              150000 non-null  object
 7   State             150000 non-null  object
 8   Region            150000 non-null  object
 9   PreferredChannel  150000 non-null  object
 10  ActivityWeight    150000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(8)
memory usage: 12.6+ MB

In [22]:
customers.describe(include="all")

,CustomerID,SignupDate,Gender,AgeBand,Segment,Tier,City,State,Region,PreferredChannel,ActivityWeight
count,150000.000000,150000,150000,150000,150000,150000,150000,150000,150000,150000,150000.000000
unique,NaN,NaN,2,4,6,3,35,17,5,7,NaN
top,NaN,NaN,Male,25-34,Young Professional,Tier-1,Mumbai,Maharashtra,North,Amazon India,NaN
freq,NaN,NaN,93179,52708,46251,56726,9812,20830,43488,49955,NaN
mean,575000.500000,2022-01-01 05:14:30.336000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
min,500001.000000,2019-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.033900
25%,537500.750000,2020-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.471700
50%,575000.500000,2022-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.767500
75%,612500.250000,2023-07-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.257100
max,650000.000000,2024-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.924100
std,43301.414527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.826324

In [23]:
customers.head()

,CustomerID,SignupDate,Gender,AgeBand,Segment,Tier,City,State,Region,PreferredChannel,ActivityWeight
0,500001,2022-03-20,Male,35-44,Young Professional,Tier-1,Hyderabad,Telangana,South,Flipkart,8.3345
1,500002,2021-10-19,Male,18-24,Student,Tier-1,Pune,Maharashtra,West,Flipkart,0.6440
2,500003,2023-10-10,Female,45+,Family Buyer,Tier-3,Raipur,Chhattisgarh,Central,Amazon India,0.3899
3,500004,2021-05-24,Female,18-24,Gamer,Tier-2,Nagpur,Maharashtra,West,Amazon India,0.4533
4,500005,2020-06-01,Female,25-34,Working Professional,Tier-3,Varanasi,Uttar Pradesh,North,Local Multi-brand Retail,0.8344

In [24]:
customers.duplicated().sum()

np.int64(0)

In [25]:
customers["CustomerID"].duplicated().sum()

np.int64(0)

In [26]:
customers["CustomerID"].nunique()

150000

In [27]:
text_cols = customers.select_dtypes(include="object").columns

for col in text_cols:
    print(f"\n{col}")
    print(customers[col].value_counts())

Gender
Gender
Male      93179
Female    56821
Name: count, dtype: int64

AgeBand
AgeBand
25-34    52708
18-24    50575
35-44    27203
45+      19514
Name: count, dtype: int64

Segment
Segment
Young Professional      46251
Student                 35755
Working Professional    24216
Family Buyer            22572
Gamer                   12073
Gift Buyer               9133
Name: count, dtype: int64

Tier
Tier
Tier-1    56726
Tier-2    55570
Tier-3    37704
Name: count, dtype: int64

City
City
Mumbai        9812
Delhi         9112
Bengaluru     8332
Hyderabad     7648
Chennai       6625
Jaipur        6554
Lucknow       5956
Indore        5873
Pune          5844
Surat         5595
Nagpur        5174
Ahmedabad     5120
Chandigarh    4767
Bhopal        4392
Kolkata       4233
Coimbatore    4116
Kochi         3721
Patna         3466
Varanasi      3458
Gwalior       3363
Siliguri      3232
Vadodara      3102
Jabalpur      3078
Mysuru        2916
Ludhiana      2854
Rajkot        2770
Jodhpur       2625
Dehradun      2579
Raipur        2333
Dhanbad       2230
Agra          2076
Trichy        1973
Bareilly      1820
Kota          1687
Asansol       1564
Name: count, dtype: int64

State
State
Maharashtra       20830
Madhya Pradesh    16706
Gujarat           16587
Uttar Pradesh     13310
Tamil Nadu        12714
Karnataka         11248
Rajasthan         10866
Delhi              9112
West Bengal        9029
Telangana          7648
Chandigarh         4767
Kerala             3721
Bihar              3466
Punjab             2854
Uttarakhand        2579
Chhattisgarh       2333
Jharkhand          2230
Name: count, dtype: int64

Region
Region
North      43488
West       37417
South      35331
Central    19039
East       14725
Name: count, dtype: int64

PreferredChannel
PreferredChannel
Amazon India                49955
Flipkart                    41956
boAt Official Website       17838
Croma                       12256
Local Multi-brand Retail    11301
Reliance Digital            10063
Vijay Sales                  6631
Name: count, dtype: int64

In [28]:
text_cols = customers.select_dtypes(include="object").columns

customers[text_cols] = customers[text_cols].apply(lambda x: x.str.strip())
customers[text_cols] = customers[text_cols].apply(lambda x: x.str.replace(r"\s+", " ", regex=True))

In [32]:
customers.to_csv("Customer_Details_Clean.csv", index=False)

In [33]:
from google.colab import files
files.download("Customer_Details_Clean.csv")

In [34]:
delivery = pd.read_csv("Delivery_Partner_Data.csv")

In [35]:
delivery.head()

,DeliveryPartnerID,PartnerName,HomeCity,Region,VehicleType,Rating,ExperienceYears
0,8001,Rider_001,Varanasi,Central,Electric Bike,4.5,2
1,8002,Rider_002,Indore,North,Van,4.8,9
2,8003,Rider_003,Ludhiana,West,Bike,4.7,8
3,8004,Rider_004,Delhi,East,Scooter,4.4,11
4,8005,Rider_005,Kochi,North,Electric Bike,4.6,10

In [36]:
delivery.shape

(180, 7)

In [37]:
delivery.columns.tolist()

['DeliveryPartnerID',
 'PartnerName',
 'HomeCity',
 'Region',
 'VehicleType',
 'Rating',
 'ExperienceYears']

In [38]:
delivery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DeliveryPartnerID  180 non-null    int64
 1   PartnerName        180 non-null    object
 2   HomeCity           180 non-null    object
 3   Region             180 non-null    object
 4   VehicleType        180 non-null    object
 5   Rating             180 non-null    float64
 6   ExperienceYears    180 non-null    int64
dtypes: float64(1), int64(2), object(4)
memory usage: 10.0+ KB

In [39]:
delivery.describe(include="all")

,DeliveryPartnerID,PartnerName,HomeCity,Region,VehicleType,Rating,ExperienceYears
count,180.000000,180,180,180,180,180.000000,180.000000
unique,NaN,180,35,5,4,NaN,NaN
top,NaN,Rider_001,Rajkot,North,Bike,NaN,NaN
freq,NaN,1,10,52,90,NaN,NaN
mean,8090.500000,NaN,NaN,NaN,NaN,4.280000,5.794444
std,52.105662,NaN,NaN,NaN,NaN,0.363164,3.362124
min,8001.000000,NaN,NaN,NaN,NaN,3.600000,1.000000
25%,8045.750000,NaN,NaN,NaN,NaN,4.000000,3.000000
50%,8090.500000,NaN,NaN,NaN,NaN,4.300000,6.000000
75%,8135.250000,NaN,NaN,NaN,NaN,4.600000,9.000000
max,8180.000000,NaN,NaN,NaN,NaN,4.900000,11.000000

In [40]:
delivery.isnull().sum()

DeliveryPartnerID    0
PartnerName          0
HomeCity             0
Region               0
VehicleType          0
Rating               0
ExperienceYears      0
dtype: int64

In [41]:
delivery.duplicated().sum()

np.int64(0)

In [42]:
delivery["DeliveryPartnerID"].nunique()

180

In [44]:
delivery["Rating"].describe()

count    180.000000
mean       4.280000
std        0.363164
min        3.600000
25%        4.000000
50%        4.300000
75%        4.600000
max        4.900000
Name: Rating, dtype: float64

In [45]:
delivery[delivery["Rating"] < 1]

Empty DataFrame
Columns: [DeliveryPartnerID, PartnerName, HomeCity, Region, VehicleType, Rating, ExperienceYears]
Index: []

In [46]:
delivery[delivery["ExperienceYears"] < 0]

Empty DataFrame
Columns: [DeliveryPartnerID, PartnerName, HomeCity, Region, VehicleType, Rating, ExperienceYears]
Index: []

In [47]:
text_cols = delivery.select_dtypes(include="object").columns

for col in text_cols:
    print(f"\n{col}")
    print(delivery[col].value_counts())

PartnerName
PartnerName
Rider_001    1
Rider_002    1
Rider_003    1
Rider_004    1
Rider_005    1
            ..
Rider_176    1
Rider_177    1
Rider_178    1
Rider_179    1
Rider_180    1
Name: count, Length: 180, dtype: int64

HomeCity
HomeCity
Rajkot        10
Raipur         9
Jaipur         8
Jodhpur        7
Asansol        7
Indore         7
Kochi          7
Dehradun       7
Mumbai         7
Bareilly       7
Ludhiana       6
Surat          6
Trichy         6
Ahmedabad      6
Bhopal         6
Chandigarh     5
Pune           5
Gwalior        5
Kolkata        5
Patna          5
Chennai        5
Varanasi       4
Siliguri       4
Dhanbad        4
Bengaluru      4
Jabalpur       4
Vadodara       4
Mysuru         4
Agra           3
Hyderabad      3
Lucknow        3
Nagpur         2
Kota           2
Coimbatore     2
Delhi          1
Name: count, dtype: int64

Region
Region
North      52
West       42
South      38
East       31
Central    17
Name: count, dtype: int64

VehicleType
VehicleType
Bike             90
Scooter          42
Electric Bike    27
Van              21
Name: count, dtype: int64

In [49]:
delivery.to_csv("Delivery_Partner_Data_Clean.csv", index=False)

In [50]:
from google.colab import files
files.download("Delivery_Partner_Data_Clean.csv")

In [51]:
products = pd.read_csv("Product_Details.csv")

In [52]:
products.head()

,ProductID,Brand,Category,SubCategory,ProductName,HeroFlag,LaunchYear,MRP,CostPrice,PopularityWeight,DemandCluster
0,1001,boAt,True Wireless Earbuds,Airdopes,boAt Airdopes 141,1,2024,9900.0,4445.96,0.138664,Hero
1,1002,boAt,True Wireless Earbuds,Airdopes,boAt Airdopes 161,1,2025,6470.0,3185.78,0.061200,Hero
2,1003,boAt,True Wireless Earbuds,Airdopes,boAt Airdopes 131,1,2025,1490.0,770.25,0.037928,Hero
3,1004,boAt,True Wireless Earbuds,Airdopes,boAt Airdopes 181 Pro,1,2023,9050.0,3979.68,0.027011,Hero
4,1005,boAt,True Wireless Earbuds,Airdopes,boAt Airdopes 311 Pro,0,2022,7670.0,3975.72,0.005931,Core

In [53]:
products.shape

(106, 11)

In [54]:
products.columns.tolist()

['ProductID',
 'Brand',
 'Category',
 'SubCategory',
 'ProductName',
 'HeroFlag',
 'LaunchYear',
 'MRP',
 'CostPrice',
 'PopularityWeight',
 'DemandCluster']

In [55]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ProductID         106 non-null    int64
 1   Brand             106 non-null    object
 2   Category          106 non-null    object
 3   SubCategory       106 non-null    object
 4   ProductName       106 non-null    object
 5   HeroFlag          106 non-null    int64
 6   LaunchYear        106 non-null    int64
 7   MRP               106 non-null    float64
 8   CostPrice         106 non-null    float64
 9   PopularityWeight  106 non-null    float64
 10  DemandCluster     106 non-null    object
dtypes: float64(3), int64(3), object(5)
memory usage: 9.2+ KB

In [56]:
products.describe(include="all")

,ProductID,Brand,Category,SubCategory,ProductName,HeroFlag,LaunchYear,MRP,CostPrice,PopularityWeight,DemandCluster
count,106.000000,106,106,106,106,106.000000,106.000000,106.000000,106.000000,106.000000,106
unique,NaN,1,13,13,105,NaN,NaN,NaN,NaN,NaN,3
top,NaN,boAt,True Wireless Earbuds,Airdopes,boAt Rockerz 650 Pro,NaN,NaN,NaN,NaN,NaN,Hero
freq,NaN,106,28,28,2,NaN,NaN,NaN,NaN,NaN,46
mean,1053.500000,NaN,NaN,NaN,NaN,0.433962,2023.292453,5763.962264,3093.093868,0.009434,NaN
std,30.743563,NaN,NaN,NaN,NaN,0.497974,1.129408,4883.808366,3204.845389,0.017946,NaN
min,1001.000000,NaN,NaN,NaN,NaN,0.000000,2021.000000,680.000000,280.020000,0.000695,NaN
25%,1027.250000,NaN,NaN,NaN,NaN,0.000000,2023.000000,2820.000000,1307.305000,0.001154,NaN
50%,1053.500000,NaN,NaN,NaN,NaN,0.000000,2023.000000,4855.000000,2357.250000,0.002424,NaN
75%,1079.750000,NaN,NaN,NaN,NaN,1.000000,2024.000000,6927.500000,3688.225000,0.010153,NaN
max,1106.000000,NaN,NaN,NaN,NaN,1.000000,2025.000000,29300.000000,20725.470000,0.138664,NaN

In [57]:
products.isnull().sum()

ProductID           0
Brand               0
Category            0
SubCategory         0
ProductName         0
HeroFlag            0
LaunchYear          0
MRP                 0
CostPrice           0
PopularityWeight    0
DemandCluster       0
dtype: int64

In [58]:
products.duplicated().sum()

np.int64(0)

In [59]:
products["ProductID"].nunique()

106

In [60]:
products.apply(lambda x: x.astype(str).str.strip().eq("").sum())

ProductID           0
Brand               0
Category            0
SubCategory         0
ProductName         0
HeroFlag            0
LaunchYear          0
MRP                 0
CostPrice           0
PopularityWeight    0
DemandCluster       0
dtype: int64

In [61]:
text_cols = products.select_dtypes(include="object").columns

products[text_cols] = products[text_cols].apply(
    lambda x: x.str.strip()
)

products[text_cols] = products[text_cols].apply(
    lambda x: x.str.replace(r"\s+", " ", regex=True)
)

In [62]:
text_cols = products.select_dtypes(include="object").columns

for col in text_cols:
    print(f"\n{col}")
    print(products[col].value_counts())

Brand
Brand
boAt    106
Name: count, dtype: int64

Category
Category
True Wireless Earbuds    28
Neckbands                14
Smart Watches            14
Headphones               10
Wireless Speakers        10
Soundbars                 6
Power Banks               5
Wired Earphones           5
Gaming Headphones         4
Chargers & Cables         4
Party Speakers            2
Projectors                2
Dashcams                  2
Name: count, dtype: int64

SubCategory
SubCategory
Airdopes                 28
Neckbands                14
Wave / Lunar / Ultima    14
Rockerz                  10
Stone                    10
Soundbars                 6
Energyshroom              5
Bassheads                 5
Gaming Rockerz            4
Accessories               4
PartyPal                  2
Cinehead                  2
Drive                     2
Name: count, dtype: int64

ProductName
ProductName
boAt Rockerz 650 Pro            2
boAt Airdopes 161               1
boAt Airdopes 131               1
boAt Airdopes 181 Pro           1
boAt Airdopes 311 Pro           1
                               ..
boAt Drive X2                   1
boAt EnergyBoost 20W Charger    1
boAt 33W GaN Charger            1
boAt Type-C Cable               1
boAt Braided USB-C Cable        1
Name: count, Length: 105, dtype: int64

DemandCluster
DemandCluster
Hero        46
LongTail    35
Core        25
Name: count, dtype: int64

In [63]:
products[products["ProductName"] == "boAt Rockerz 650 Pro"]

,ProductID,Brand,Category,SubCategory,ProductName,HeroFlag,LaunchYear,MRP,CostPrice,PopularityWeight,DemandCluster
33,1034,boAt,Neckbands,Neckbands,boAt Rockerz 650 Pro,0,2021,2590.0,1152.18,0.002360,Core
58,1059,boAt,Headphones,Rockerz,boAt Rockerz 650 Pro,1,2023,5910.0,2927.52,0.010261,Hero

In [64]:
products[products["CostPrice"] > products["MRP"]]

Empty DataFrame
Columns: [ProductID, Brand, Category, SubCategory, ProductName, HeroFlag, LaunchYear, MRP, CostPrice, PopularityWeight, DemandCluster]
Index: []

In [65]:
products["Margin"] = products["MRP"] - products["CostPrice"]
products["Margin"].describe()

count     106.000000
mean     2670.868396
std      1800.041120
min       354.700000
25%      1418.265000
50%      2427.685000
75%      3312.990000
max      9479.550000
Name: Margin, dtype: float64

In [66]:
products[products["Margin"] < 0]

Empty DataFrame
Columns: [ProductID, Brand, Category, SubCategory, ProductName, HeroFlag, LaunchYear, MRP, CostPrice, PopularityWeight, DemandCluster, Margin]
Index: []

In [67]:
products["HeroFlag"].value_counts()

HeroFlag
0    60
1    46
Name: count, dtype: int64

In [68]:
products["LaunchYear"].value_counts().sort_index()

LaunchYear
2021     6
2022    20
2023    35
2024    27
2025    18
Name: count, dtype: int64

In [69]:
products[products["PopularityWeight"] < 0]

Empty DataFrame
Columns: [ProductID, Brand, Category, SubCategory, ProductName, HeroFlag, LaunchYear, MRP, CostPrice, PopularityWeight, DemandCluster, Margin]
Index: []

In [70]:
products.to_csv("Product_Details_Clean.csv", index=False)

In [71]:
from google.colab import files
files.download("Product_Details_Clean.csv")

In [74]:
Saleschannel = pd.read_csv("Sales_Channel.csv")

In [75]:
Saleschannel.head()

,ChannelID,ChannelName,ChannelType,ChannelScope,RegionScope,BaseShare
0,1,Amazon India,Online Marketplace,Online,National,0.34
1,2,Flipkart,Online Marketplace,Online,National,0.28
2,3,boAt Official Website,D2C,Online,National,0.12
3,4,Croma,Offline Retail,Offline,Multi-city,0.09
4,5,Reliance Digital,Offline Retail,Offline,Multi-city,0.07

In [76]:
Saleschannel.shape

(7, 6)

In [77]:
Saleschannel.columns.tolist()

['ChannelID',
 'ChannelName',
 'ChannelType',
 'ChannelScope',
 'RegionScope',
 'BaseShare']

In [78]:
Saleschannel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ChannelID     7 non-null      int64
 1   ChannelName   7 non-null      object
 2   ChannelType   7 non-null      object
 3   ChannelScope  7 non-null      object
 4   RegionScope   7 non-null      object
 5   BaseShare     7 non-null      float64
dtypes: float64(1), int64(1), object(4)
memory usage: 468.0+ bytes

In [79]:
Saleschannel.describe(include="all")

,ChannelID,ChannelName,ChannelType,ChannelScope,RegionScope,BaseShare
count,7.000000,7,7,7,7,7.000000
unique,NaN,7,3,2,3,NaN
top,NaN,Amazon India,Offline Retail,Offline,National,NaN
freq,NaN,1,4,4,3,NaN
mean,4.000000,NaN,NaN,NaN,NaN,0.142857
std,2.160247,NaN,NaN,NaN,NaN,0.117999
min,1.000000,NaN,NaN,NaN,NaN,0.050000
25%,2.500000,NaN,NaN,NaN,NaN,0.060000
50%,4.000000,NaN,NaN,NaN,NaN,0.090000
75%,5.500000,NaN,NaN,NaN,NaN,0.200000
max,7.000000,NaN,NaN,NaN,NaN,0.340000

In [80]:
Saleschannel.isnull().sum()

ChannelID       0
ChannelName     0
ChannelType     0
ChannelScope    0
RegionScope     0
BaseShare       0
dtype: int64

In [81]:
Saleschannel.duplicated().sum()

np.int64(0)

In [82]:
Saleschannel.apply(lambda x: x.astype(str).str.strip().eq("").sum())

ChannelID       0
ChannelName     0
ChannelType     0
ChannelScope    0
RegionScope     0
BaseShare       0
dtype: int64

In [83]:
Saleschannel["ChannelID"].nunique()

7

In [84]:
text_cols = Saleschannel.select_dtypes(include="object").columns

Saleschannel[text_cols] = Saleschannel[text_cols].apply(
    lambda x: x.str.strip()
)

Saleschannel[text_cols] = Saleschannel[text_cols].apply(
    lambda x: x.str.replace(r"\s+", " ", regex=True)
)

In [85]:
text_cols = Saleschannel.select_dtypes(include="object").columns

for col in text_cols:
    print(f"\n{col}")
    print(Saleschannel[col].value_counts())

ChannelName
ChannelName
Amazon India                1
Flipkart                    1
boAt Official Website       1
Croma                       1
Reliance Digital            1
Vijay Sales                 1
Local Multi-brand Retail    1
Name: count, dtype: int64

ChannelType
ChannelType
Offline Retail        4
Online Marketplace    2
D2C                   1
Name: count, dtype: int64

ChannelScope
ChannelScope
Offline    4
Online     3
Name: count, dtype: int64

RegionScope
RegionScope
National      3
Multi-city    3
Regional      1
Name: count, dtype: int64

In [86]:
Saleschannel.to_csv("Sales_Channel_Clean.csv", index=False)

In [87]:
from google.colab import files
files.download("Sales_Channel_Clean.csv")

In [88]:
sales = pd.read_csv("Sales_Data.csv")

/tmp/ipykernel_1149/774855261.py:1: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  sales = pd.read_csv("Sales_Data.csv")

In [89]:
sales.head()

,SalesID,OrderDate,OrderHour,CustomerID,ProductID,ChannelID,DeliveryPartnerID,Quantity,GrossMRPValue,DiscountPct,...,DeliveryDays,CustomerTier,CustomerSegment,CityTier,ChannelType,IsFestivalPeriod,FestivalName,IsWeekend,ProductCategory,HeroFlag
0,1,01-01-2023,20,550151,1104,4,8129,1,1140,0.3689,...,2,Tier-2,Student,Tier-2,Offline,1,New Year Sale,1,Chargers & Cables,1
1,2,01-01-2023,17,619093,1046,4,8174,2,21500,0.4150,...,0,Tier-1,Working Professional,Tier-1,Offline,1,New Year Sale,1,Smart Watches,1
2,3,01-01-2023,16,562641,1046,1,8106,1,10750,0.5633,...,3,Tier-3,Gift Buyer,Tier-3,Online,1,New Year Sale,1,Smart Watches,1
3,4,01-01-2023,17,583589,1029,2,8159,1,2010,0.6133,...,3,Tier-1,Family Buyer,Tier-1,Online,1,New Year Sale,1,Neckbands,1
4,5,01-01-2023,8,607405,1031,1,8082,1,1160,0.4518,...,2,Tier-1,Student,Tier-1,Online,1,New Year Sale,1,Neckbands,1

In [90]:
sales.shape

(975000, 32)

In [91]:
sales.columns.tolist()

['SalesID',
 'OrderDate',
 'OrderHour',
 'CustomerID',
 'ProductID',
 'ChannelID',
 'DeliveryPartnerID',
 'Quantity',
 'GrossMRPValue',
 'DiscountPct',
 'DiscountAmount',
 'SellingPrice',
 'NetSales',
 'GSTRate',
 'GSTAmount',
 'COGS',
 'ShippingCost',
 'Profit',
 'PaymentMethod',
 'OrderStatus',
 'CancellationReason',
 'ReturnReason',
 'DeliveryDays',
 'CustomerTier',
 'CustomerSegment',
 'CityTier',
 'ChannelType',
 'IsFestivalPeriod',
 'FestivalName',
 'IsWeekend',
 'ProductCategory',
 'HeroFlag']

In [92]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 975000 entries, 0 to 974999
Data columns (total 32 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   SalesID             975000 non-null  int64
 1   OrderDate           975000 non-null  object
 2   OrderHour           975000 non-null  int64
 3   CustomerID          975000 non-null  int64
 4   ProductID           975000 non-null  int64
 5   ChannelID           975000 non-null  int64
 6   DeliveryPartnerID   975000 non-null  int64
 7   Quantity            975000 non-null  int64
 8   GrossMRPValue       975000 non-null  int64
 9   DiscountPct         975000 non-null  float64
 10  DiscountAmount      975000 non-null  float64
 11  SellingPrice        975000 non-null  float64
 12  NetSales            975000 non-null  float64
 13  GSTRate             975000 non-null  int64
 14  GSTAmount           975000 non-null  float64
 15  COGS                975000 non-null  float64
 16  ShippingCost        975000 non-null  float64
 17  Profit              975000 non-null  float64
 18  PaymentMethod       975000 non-null  object
 19  OrderStatus         975000 non-null  object
 20  CancellationReason  15785 non-null   object
 21  ReturnReason        45395 non-null   object
 22  DeliveryDays        975000 non-null  int64
 23  CustomerTier        975000 non-null  object
 24  CustomerSegment     975000 non-null  object
 25  CityTier            975000 non-null  object
 26  ChannelType         975000 non-null  object
 27  IsFestivalPeriod    975000 non-null  int64
 28  FestivalName        416058 non-null  object
 29  IsWeekend           975000 non-null  int64
 30  ProductCategory     975000 non-null  object
 31  HeroFlag            975000 non-null  int64
dtypes: float64(8), int64(13), object(11)
memory usage: 238.0+ MB

In [93]:
sales.describe(include="all")

,SalesID,OrderDate,OrderHour,CustomerID,ProductID,ChannelID,DeliveryPartnerID,Quantity,GrossMRPValue,DiscountPct,...,DeliveryDays,CustomerTier,CustomerSegment,CityTier,ChannelType,IsFestivalPeriod,FestivalName,IsWeekend,ProductCategory,HeroFlag
count,975000.000000,975000,975000.000000,975000.000000,975000.000000,975000.000000,975000.000000,975000.000000,975000.000000,975000.000000,...,975000.000000,975000,975000,975000,975000,975000.000000,416058,975000.000000,975000,975000.000000
unique,NaN,731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3,6,3,2,NaN,9,NaN,13,NaN
top,NaN,11-11-2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tier-1,Young Professional,Tier-1,Online,NaN,Big Festive Sale,NaN,True Wireless Earbuds,NaN
freq,NaN,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,402304,358472,402304,715408,NaN,176351,NaN,322860,NaN
mean,487500.500000,NaN,14.057422,575087.759241,1043.643163,2.687396,8090.537644,1.123444,7363.816595,0.409372,...,2.068177,NaN,NaN,NaN,NaN,0.426726,NaN,0.297088,NaN,0.944065
std,281458.400569,NaN,4.953023,43280.292318,35.282876,1.844708,51.955131,0.417589,6170.432946,0.149571,...,1.179029,NaN,NaN,NaN,NaN,0.494602,NaN,0.456976,NaN,0.229797
min,1.000000,NaN,0.000000,500001.000000,1001.000000,1.000000,8001.000000,1.000000,680.000000,0.040000,...,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,0.000000
25%,243750.750000,NaN,10.000000,537577.000000,1003.000000,1.000000,8046.000000,1.000000,2930.000000,0.303600,...,1.000000,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,1.000000
50%,487500.500000,NaN,14.000000,575104.500000,1043.000000,2.000000,8091.000000,1.000000,6470.000000,0.408400,...,2.000000,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,1.000000
75%,731250.250000,NaN,18.000000,612614.250000,1077.000000,4.000000,8136.000000,1.000000,9900.000000,0.514900,...,3.000000,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,1.000000
max,975000.000000,NaN,23.000000,650000.000000,1106.000000,7.000000,8180.000000,4.000000,117200.000000,0.780000,...,7.000000,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,1.000000

In [94]:
sales.isnull().sum()

SalesID                    0
OrderDate                  0
OrderHour                  0
CustomerID                 0
ProductID                  0
ChannelID                  0
DeliveryPartnerID          0
Quantity                   0
GrossMRPValue              0
DiscountPct                0
DiscountAmount             0
SellingPrice               0
NetSales                   0
GSTRate                    0
GSTAmount                  0
COGS                       0
ShippingCost               0
Profit                     0
PaymentMethod              0
OrderStatus                0
CancellationReason    959215
ReturnReason          929605
DeliveryDays               0
CustomerTier               0
CustomerSegment            0
CityTier                   0
ChannelType                0
IsFestivalPeriod           0
FestivalName          558942
IsWeekend                  0
ProductCategory            0
HeroFlag                   0
dtype: int64

In [95]:
sales.duplicated().sum()

np.int64(0)

In [96]:
sales.apply(lambda x: x.astype(str).str.strip().eq("").sum())

SalesID               0
OrderDate             0
OrderHour             0
CustomerID            0
ProductID             0
ChannelID             0
DeliveryPartnerID     0
Quantity              0
GrossMRPValue         0
DiscountPct           0
DiscountAmount        0
SellingPrice          0
NetSales              0
GSTRate               0
GSTAmount             0
COGS                  0
ShippingCost          0
Profit                0
PaymentMethod         0
OrderStatus           0
CancellationReason    0
ReturnReason          0
DeliveryDays          0
CustomerTier          0
CustomerSegment       0
CityTier              0
ChannelType           0
IsFestivalPeriod      0
FestivalName          0
IsWeekend             0
ProductCategory       0
HeroFlag              0
dtype: int64

In [97]:
sales["SalesID"].nunique()

975000

In [100]:
sales["OrderDate"] = pd.to_datetime(
    sales["OrderDate"],
    dayfirst=True
)

In [101]:
sales["OrderDate"].describe()

count                           975000
mean     2024-01-10 13:38:19.923692288
min                2023-01-01 00:00:00
25%                2023-07-20 00:00:00
50%                2024-01-01 00:00:00
75%                2024-07-19 00:00:00
max                2024-12-31 00:00:00
Name: OrderDate, dtype: object

In [102]:
sales["Quantity"].describe()

count    975000.000000
mean          1.123444
std           0.417589
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Quantity, dtype: float64

In [103]:
sales[sales["Quantity"] <= 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [104]:
sales["DiscountPct"].describe()

count    975000.000000
mean          0.409372
std           0.149571
min           0.040000
25%           0.303600
50%           0.408400
75%           0.514900
max           0.780000
Name: DiscountPct, dtype: float64

In [105]:
sales[
    (sales["DiscountPct"] < 0) |
    (sales["DiscountPct"] > 1)
]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [106]:
sales[sales["GrossMRPValue"] <= 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [107]:
sales[sales["SellingPrice"] <= 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [108]:
sales[sales["NetSales"] <= 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [109]:
sales["GSTRate"].value_counts()

GSTRate
18    975000
Name: count, dtype: int64

In [110]:
sales["ShippingCost"].describe()

count    975000.000000
mean         55.031713
std          17.661132
min          12.000000
25%          43.830000
50%          56.930000
75%          67.650000
max         113.940000
Name: ShippingCost, dtype: float64

In [111]:
sales[
    sales["ShippingCost"] < 0
]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [112]:
sales["Profit"].describe()

count    975000.000000
mean        598.371936
std        1530.006718
min      -42347.110000
25%         -72.120000
50%         339.035000
75%        1209.712500
max       28087.350000
Name: Profit, dtype: float64

In [113]:
sales[
    sales["Profit"] < 0
]

,SalesID,OrderDate,OrderHour,CustomerID,ProductID,ChannelID,DeliveryPartnerID,Quantity,GrossMRPValue,DiscountPct,...,DeliveryDays,CustomerTier,CustomerSegment,CityTier,ChannelType,IsFestivalPeriod,FestivalName,IsWeekend,ProductCategory,HeroFlag
2,3,2023-01-01,16,562641,1046,1,8106,1,10750,0.5633,...,3,Tier-3,Gift Buyer,Tier-3,Online,1,New Year Sale,1,Smart Watches,1
3,4,2023-01-01,17,583589,1029,2,8159,1,2010,0.6133,...,3,Tier-1,Family Buyer,Tier-1,Online,1,New Year Sale,1,Neckbands,1
6,7,2023-01-01,23,578471,1043,1,8146,1,6530,0.5761,...,2,Tier-2,Family Buyer,Tier-2,Online,1,New Year Sale,1,Smart Watches,1
7,8,2023-01-01,13,596487,1103,2,8142,1,1150,0.6066,...,4,Tier-3,Young Professional,Tier-3,Online,1,New Year Sale,1,Chargers & Cables,1
8,9,2023-01-01,21,578525,1096,1,8175,2,7340,0.5077,...,3,Tier-2,Student,Tier-2,Online,1,New Year Sale,1,Gaming Headphones,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974990,974991,2024-12-31,19,544205,1067,2,8161,1,9710,0.6329,...,2,Tier-1,Young Professional,Tier-1,Online,1,Year End Sale,0,Wireless Speakers,1
974991,974992,2024-12-31,17,575973,1002,1,8145,2,12940,0.6193,...,3,Tier-2,Working Professional,Tier-2,Online,1,Year End Sale,0,True Wireless Earbuds,1
974993,974994,2024-12-31,8,550980,1088,2,8027,4,2880,0.6856,...,2,Tier-2,Gamer,Tier-2,Online,1,Year End Sale,0,Wired Earphones,1
974998,974999,2024-12-31,12,505714,1067,1,8049,1,9710,0.6128,...,1,Tier-2,Student,Tier-2,Online,1,Year End Sale,0,Wireless Speakers,1
974999,975000,2024-12-31,21,609496,1098,1,8042,1,5910,0.6097,...,2,Tier-2,Working Professional,Tier-2,Online,1,Year End Sale,0,Party Speakers,1

In [114]:
pd.crosstab(
    sales["IsFestivalPeriod"],
    sales["FestivalName"],
    dropna=False
)

FestivalName,Big Festive Sale,Holi Sale,Independence Day Sale,Monsoon Deals,New Year Sale,Raksha Bandhan Sale,Republic Day Sale,Summer Sale,Year End Sale,NaN
IsFestivalPeriod,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,558942
1,176351,27705,20144,39950,21025,26135,24262,42307,38179,0

In [115]:
pd.crosstab(
    sales["OrderStatus"],
    sales["CancellationReason"],
    dropna=False
)

CancellationReason,Address issue,COD not confirmed,Customer cancelled,Customer changed mind,Customer unreachable,Payment failed,Stockout,Store stockout,NaN
OrderStatus,,,,,,,,,
Cancelled,3913,2928,1069,580,2382,1559,2337,1017,0
Delivered,0,0,0,0,0,0,0,0,913820
Returned,0,0,0,0,0,0,0,0,45395

In [116]:
pd.crosstab(
    sales["OrderStatus"],
    sales["ReturnReason"],
    dropna=False
)

ReturnReason,App sync issue,Battery drain,Cable defect,Capacity mismatch,Changed mind,Charging defect,Charging issue,Comfort issue,Compatibility issue,Connectivity issue,...,Recording issue,Resolution issue,Setup issue,Sound distortion,Sound imbalance,Sound issue,Strap/fit issue,Wrong length,Wrong variant,NaN
OrderStatus,,,,,,,,,,,,,,,,,,,,,
Cancelled,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15785
Delivered,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,913820
Returned,2073,1422,229,287,11390,4431,272,1365,259,4390,...,40,63,61,1148,5487,232,2061,266,1412,0

In [117]:
sales["SalesID"].nunique()

975000

In [118]:
sales["Quantity"].describe()

count    975000.000000
mean          1.123444
std           0.417589
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Quantity, dtype: float64

In [119]:
sales[sales["Quantity"] <= 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [120]:
sales["DiscountPct"].describe()

count    975000.000000
mean          0.409372
std           0.149571
min           0.040000
25%           0.303600
50%           0.408400
75%           0.514900
max           0.780000
Name: DiscountPct, dtype: float64

In [121]:
sales[(sales["DiscountPct"] < 0) | (sales["DiscountPct"] > 1)]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [122]:
sales["GSTRate"].value_counts()

GSTRate
18    975000
Name: count, dtype: int64

In [123]:
sales["Profit"].describe()

count    975000.000000
mean        598.371936
std        1530.006718
min      -42347.110000
25%         -72.120000
50%         339.035000
75%        1209.712500
max       28087.350000
Name: Profit, dtype: float64

In [124]:
# Number of loss-making orders
(sales["Profit"] < 0).sum()

np.int64(283173)

In [125]:
# Percentage of loss-making orders
((sales["Profit"] < 0).mean() * 100).round(2)

np.float64(29.04)

In [126]:
sales[sales["SellingPrice"] > sales["GrossMRPValue"]]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [127]:
sales[sales["DiscountAmount"] < 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [128]:
sales[sales["ShippingCost"] < 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [129]:
sales[sales["COGS"] < 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [130]:
sales[sales["GSTAmount"] < 0]

Empty DataFrame
Columns: [SalesID, OrderDate, OrderHour, CustomerID, ProductID, ChannelID, DeliveryPartnerID, Quantity, GrossMRPValue, DiscountPct, DiscountAmount, SellingPrice, NetSales, GSTRate, GSTAmount, COGS, ShippingCost, Profit, PaymentMethod, OrderStatus, CancellationReason, ReturnReason, DeliveryDays, CustomerTier, CustomerSegment, CityTier, ChannelType, IsFestivalPeriod, FestivalName, IsWeekend, ProductCategory, HeroFlag]
Index: []

[0 rows x 32 columns]

In [131]:
sales.to_csv("Sales_Data_Clean.csv", index=False)

In [132]:
from google.colab import files
files.download("Sales_Data_Clean.csv")